terraform/aws/development-infrastructure/nbs-legacy/README.md
terraform/aws/development-infrastructure/nbs-legacy/main.tf
terraform/aws/development-infrastructure/nbs-legacy/outputs.tf
terraform/aws/development-infrastructure/nbs-legacy/variables.tf

add nbs-legacy module

---

scripts/observability/nbs-test-api/README.md
scripts/observability/nbs-test-api/nbs-test-api.sh

cleaned up output unless debug is on, added README.md file with description and arguments

productionize smoke test

---

terraform/aws/development-infrastructure/nbs-legacy/main.tf

in place.
This module was used in the atd->fts1 account setup.  I changed the source on that branch to predict this change would be available as 1.0.4

Added RDS dependency AND windows reboot to make sure delay is actually

---

scripts/install/aws_cloudshell_quickstart/02_cloudshell_check_install_prereq.sh

tweak script to use arguments to "-y" to approve all installs

added -y and -1 flags and usage statement to allow no prompt and quieter output

---

scripts/observability/nbs-test-api/nbs-test-api.sh

cleanup errors on quoting and removed a couple commented lines, these errors made it into zip, not sure how the tested version got broken

somehow had some extraneous quotes make it into git

---

terraform/aws/app-infrastructure/eks-nbs/helm.tf
terraform/aws/app-infrastructure/eks-nbs/irsa.tf
terraform/aws/app-infrastructure/eks-nbs/locals.tf
terraform/aws/app-infrastructure/eks-nbs/main.tf
terraform/aws/app-infrastructure/eks-nbs/namespaces.tf

Fix naming for some terraform resource. Updated bootstrap of cert manager to allow OIDC for dns01 resolver

Cnpt 1554 and CNPT 1557 name fixes and cert manager

---

scripts/observability/nbs-test-webui/nbs-test-webui.sh

can be prettied up but it works and exits with zero status if login and advanced search returns non-zero results
exits with 1 if login fails 
exits with 2 is search doesn't return non-zero results

Cmoss update smoke tests webui

---

terraform/aws/samples/NBS7_standard/msk.tf

changed source to relative path, no shared vpn cidr

Cmoss add latest msk to template

---

terraform/aws/samples/NBS7_standard/fluentbit.tf
terraform/aws/samples/NBS7_standard/prometheus.tf
terraform/aws/samples/NBS7_standard/s3-buckets.tf
terraform/aws/samples/NBS7_standard/variables.tf
terraform/aws/samples/NBS7_standard/vpc-endpoints.tf

merging some of the updates of the deployment files

Cmoss update samples for release

---

scripts/install/aws_cloudshell_quickstart/05_cloudshell_get_tfvars_values_from_existing_environment_update_inputs_file.sh
scripts/observability/nbs-test-webui/README.md
scripts/observability/nbs-test-webui/nbs-test-webui.sh
terraform/aws/app-infrastructure/vpc/variables.tf
terraform/aws/samples/NBS7_standard/inputs.tfvars
terraform/aws/samples/NBS7_standard/variables.tf
terraform/aws/samples/NBS7_standard/vpc-modern.tf

fixed bugs in 7.2.0 dry run, msk volume size, vpc modern name, also
tweaked inputs for a typo and search and replaceable example templates

Cmoss updates found during 7.2 dryrun take2

---

.github/workflows/create-github-draft-release.yaml

Creates the workflow for automated draft releases. It is a manual trigger through the Actions tab.

create draft release

---

.github/workflows/create-github-draft-release.yaml

Updating draft release workflow to get latest changes.

update draft release workflow

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/02_cloudshell_check_install_prereq.sh
scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/07_cloudshell_setup_kubernetes.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_customize_helm_charts.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/13_cloudshell_cleanup_helm.sh

added a bit of usefulness to prereq install and general cleanup

Cmoss update quickstart scripts

---

scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh

can be used for Data ingestion and data reporting containers

added kafka logic and control flags to fetching values for helm

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/06_cloudshell_run_terraform.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_install_helm_nginx-ingress.sh
scripts/install/aws_cloudshell_quickstart/11_cloudshell_install_acme.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/13_cloudshell_cleanup_helm.sh
scripts/install/aws_cloudshell_quickstart/14_cloudshell_cleanup_destroy_terraform.sh

initial changes for 7.4.0

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/06_cloudshell_run_terraform.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_install_helm_nginx-ingress.sh
scripts/install/aws_cloudshell_quickstart/10_cloudshell_update_dns_after_nlb_created.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
terraform/aws/samples/NBS7_standard/eks.tf
terraform/aws/samples/NBS7_standard/inputs.tfvars
terraform/aws/samples/NBS7_standard/variables.tf

missed a couple of files with last PR in samples
Also updated several scripts in quickstart

Cmoss changes4release74 20240429

---

README.md

Iteration 1 of improvements to README.md in root directory. Please review, approve and suggest updates.

Sgz update root readme

---

terraform/azure/modules/0_landing_zone/agw-public/nsg.tf
terraform/azure/modules/0_landing_zone/agw-public/variables.tf
terraform/azure/modules/1_nbs6/agw-private/nsg.tf

Added NSG creation for public and private AGW. This will allow us to managed Network Security Groups from TF for both private and public AGW.

Added NSG creation for public and private AGW.

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/07_cloudshell_setup_kubernetes.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/11_cloudshell_install_acme.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/13_cloudshell_cleanup_helm.sh
scripts/install/aws_cloudshell_quickstart/14_cloudshell_cleanup_destroy_terraform.sh

these scripts can be used to help with a initial deployment, they were written for cloudshell but now can be useful in any bash (bourne?) shell

making these scripts work outside cloudshell, add more logic, checks

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/13_cloudshell_cleanup_helm.sh

minor change to debugging and allow overwrite of zero length files

Cmoss 20240611 prep for 7.4.2

---

terraform/azure/modules/2_nbs7/private-dns-zone/main.tf
terraform/azure/modules/2_nbs7/private-dns-zone/variables.tf
terraform/azure/modules/2_nbs7/storage-account/main.tf

Change storage accounts and dns zones to be more flexible.

Sgz update logic storage acc

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/06_cloudshell_run_terraform.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_install_helm_nginx-ingress.sh
scripts/install/aws_cloudshell_quickstart/11_cloudshell_install_acme.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/14_cloudshell_cleanup_destroy_terraform.sh
terraform/aws/app-infrastructure/eks-nbs/variables.tf

changing the module default since not used in recommended installation at the moment

default to false for argocd

---

scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/05_cloudshell_get_tfvars_update_inputs_file.sh
scripts/install/aws_cloudshell_quickstart/06_cloudshell_run_terraform.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
terraform/aws/samples/NBS7_existing_network/README.md
terraform/aws/samples/NBS7_existing_network/efs.tf
terraform/aws/samples/NBS7_existing_network/eks.tf
terraform/aws/samples/NBS7_existing_network/fluentbit.tf
terraform/aws/samples/NBS7_existing_network/kms.tf
terraform/aws/samples/NBS7_existing_network/msk.tf
terraform/aws/samples/NBS7_existing_network/nbs-modern-vpc.tf
terraform/aws/samples/NBS7_existing_network/prometheus.tf
terraform/aws/samples/NBS7_existing_network/s3-buckets.tf
terraform/aws/samples/NBS7_existing_network/terraform.tf
terraform/aws/samples/NBS7_existing_network/variables.tf
terraform/aws/samples/NBS7_existing_network/vpc-endpoints.tf
terraform/aws/samples/NBS7_standard/fluentbit.tf
terraform/aws/samples/NBS7_standard/variables.tf

scripts and new sample should not impact any documented process, the new sample dir is a work in progress

Cmoss prep for 7 4 3b

---

terraform/aws/samples/NBS7_existing_network/data.tf
terraform/aws/samples/NBS7_existing_network/efs.tf
terraform/aws/samples/NBS7_existing_network/eks.tf
terraform/aws/samples/NBS7_existing_network/msk.tf
terraform/aws/samples/NBS7_existing_network/nbs-modern-vpc.tf.disabled
terraform/aws/samples/NBS7_existing_network/vpc-endpoints.tf
terraform/aws/samples/NBS7_standard/fluentbit.tf
terraform/aws/samples/NBS7_standard/s3-buckets.tf
terraform/aws/samples/NBS7_standard/variables.tf

don't assume we need to create vpc, peering and routing
use data sources and variables

Cmoss samples novpc

---

terraform/aws/app-infrastructure/linkerd/helm.tf
terraform/aws/app-infrastructure/linkerd/variables.tf

minor changes, tested in new environment twice

fixed repo and path for control-plane

---

terraform/aws/samples/README.md

Cmoss 20240710b

---

terraform/aws/app-infrastructure/aws-prometheus-grafana/modules/prometheus-helm/values.yaml
terraform/aws/app-infrastructure/linkerd/helm.tf
terraform/aws/app-infrastructure/linkerd/variables.tf
terraform/aws/development-infrastructure/nbs-legacy/nbs-classic-ecs.tf
terraform/aws/samples/README.md
terraform/azure/modules/3_applications/linkerd/helm.tf
terraform/azure/modules/3_applications/linkerd/variables.tf

Think this may fail because release is a protected branch

merge updates from main to release tag

---

terraform/aws/app-infrastructure/msk/main.tf

https://cdc-nbs.atlassian.net/jira/software/c/projects/CNAT/boards/115?selectedIssue=CNAT-233

msk configurations update

---

terraform/aws/development-infrastructure/nbs-legacy/main.tf
terraform/aws/development-infrastructure/nbs-legacy/variables.tf

Reverts CDCgov/NEDSS-Infrastructure#152, this breaks main, somehow the line trailing user data was not part of commit, needs more testing

Revert "try wrapping user data in a enable flag"

---

scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_install_helm_nginx-ingress.sh
scripts/install/aws_cloudshell_quickstart/11_cloudshell_install_acme.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/13_cloudshell_cleanup_helm.sh

added 10 containers and some scripting cleanup

Cmoss 20240909 dry run changes

---

terraform/aws/samples/NBS6_standalone/inputs.tfvars.tpl

Cmoss 20241003 nbs6poc

---

terraform/aws/samples/NBS6_7/README.md
terraform/aws/samples/NBS6_7/dns.tf
terraform/aws/samples/NBS6_7/ebs.tf
terraform/aws/samples/NBS6_7/efs.tf
terraform/aws/samples/NBS6_7/eks.tf
terraform/aws/samples/NBS6_7/fluentbit.tf
terraform/aws/samples/NBS6_7/inputs.tfvars.tpl
terraform/aws/samples/NBS6_7/kms.tf
terraform/aws/samples/NBS6_7/linkerd.tf
terraform/aws/samples/NBS6_7/msk.tf
terraform/aws/samples/NBS6_7/nbs-legacy-vpc.tf
terraform/aws/samples/NBS6_7/nbs-legacy.tf
terraform/aws/samples/NBS6_7/nbs-modern-vpc.tf
terraform/aws/samples/NBS6_7/prometheus.tf.disabled
terraform/aws/samples/NBS6_7/rds.tf
terraform/aws/samples/NBS6_7/s3-buckets.tf
terraform/aws/samples/NBS6_7/synthetics-canary.tf.disabled
terraform/aws/samples/NBS6_7/terraform.tf.tpl
terraform/aws/samples/NBS6_7/variables.tf
terraform/aws/samples/NBS6_7/vpc-endpoints.tf
terraform/aws/samples/NBS6_standalone/README.md
terraform/aws/samples/README.md

Adding samples directory for NBS 6 and 7 PoC, updated some readmes

Cmoss 20241004 nbs6poc

---

scripts/install/aws_cloudshell_quickstart/create_sql_and_keycloak_json_from_csv_for_new_users.sh

deals with line formatted with CR/LF

tweaked usage, initial a password, address reading dos formatted csv

---

scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
terraform/aws/samples/NBS6_7/inputs.tfvars.tpl
terraform/aws/samples/NBS6_7/nbs-legacy.tf
terraform/aws/samples/NBS6_7/variables-6.tf
terraform/aws/samples/NBS6_7/variables-common.tf

sample has typical STLT setup as defaults

Cmoss 20241218 tweak dns during dry run

---

scripts/install/aws_cloudshell_quickstart/01_cloudshell_get_zips_and_extract.sh
scripts/install/aws_cloudshell_quickstart/04_cloudshell_copy_and_update_terraform_files.sh
scripts/install/aws_cloudshell_quickstart/05_cloudshell_get_tfvars_update_inputs_file.sh
scripts/install/aws_cloudshell_quickstart/06_cloudshell_run_terraform.sh
scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
scripts/install/aws_cloudshell_quickstart/09_cloudshell_install_helm_nginx-ingress.sh
scripts/install/aws_cloudshell_quickstart/10_cloudshell_update_dns_after_nlb_created.sh
scripts/install/aws_cloudshell_quickstart/11_cloudshell_install_acme.sh
scripts/install/aws_cloudshell_quickstart/12_cloudshell_install_microservices.sh
scripts/install/aws_cloudshell_quickstart/14_cloudshell_cleanup_destroy_terraform.sh
scripts/install/aws_cloudshell_quickstart/create_sql_and_keycloak_json_from_csv_for_new_users.sh
terraform/aws/samples/NBS6_7/README.md
terraform/aws/samples/README.md

Cmoss 20250123 update for 7.8.2, add password to utility script 

---

terraform/aws/development-infrastructure/nbs-legacy/main.tf

Fixd bug preventing wildfly from starting and JVM memory being set

fix mem bug

---

terraform/aws/development-infrastructure/nbs-legacy/main.tf
terraform/aws/development-infrastructure/nbs-legacy/parameter_store.tf
terraform/aws/development-infrastructure/nbs-legacy/variables.tf

Add PHCRImporter as scheduled task with input user, tested in fts1

Sgz phcrimporter update

---

terraform/aws/development-infrastructure/sftp/README.md
terraform/aws/development-infrastructure/sftp/lambda/copy_to_inbox.py
terraform/aws/development-infrastructure/sftp/lambda/summary_report.py
terraform/aws/development-infrastructure/sftp/main.tf
terraform/aws/development-infrastructure/sftp/outputs.tf
terraform/aws/development-infrastructure/sftp/terraform.tfvars.tpl
terraform/aws/development-infrastructure/sftp/variables.tf

first pass, look at readme for todo items, lambdas are untested but the workflow concept may be worthwhile

Cmoss 20250327 sftp transfer service

---

scripts/install/aws_cloudshell_quickstart/08_cloudshell_get_helm_values_from_existing_environment_update_charts.sh
terraform/aws/app-infrastructure/sas9/ec2-files/scripts/sas_file_fix.sh
terraform/aws/app-infrastructure/sas9/ec2-files/scripts/sas_setup_local.sh
terraform/aws/app-infrastructure/sas9/ec2-files/templates/etc/odbc.ini.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/etc/systemd/system/sas_spawner.env.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/home/SAS/.bashrc.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/home/SAS/.odbc.ini.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/home/SAS/SAS_user_cronjobs.cron.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/opt/wildfly-10.0.0.Final/nedssdomain/Nedss/report/autoexec.sas.template
terraform/aws/app-infrastructure/sas9/ec2-files/templates/root/update_config.sql.template

imported files from ec2 to be added to builder ami
templates and a couple scripts

Cmoss 20250428 misc

---

terraform/aws/development-infrastructure/sftp-lambda-preprocessor/README.md
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_csv.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_dat.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_obr.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/main.tf
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/outputs.tf
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/regenerate_lambda_zips.sh
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/validate_hl7_upload.sh
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/variables.tf

refactored csv2hl7 to be more general purpose

Cmoss 20250512 csv2hl7

---

terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_csv/lambda_split_csv.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_dat/lambda_split_dat.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_obr/lambda_split_obr.py
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/main.tf
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/s3_notifications.tf.disable
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/utilities/add_s3_notification.sh
terraform/aws/development-infrastructure/sftp-lambda-preprocessor/utilities/export_s3_notifications.sh

moved s3 notifications out of main.tf (can manage outside of terraform if needed)
also added library to allow special characters in s3 objects

Cmoss 20250530 sftp lambda

---

scripts/utilities/sftp_transfer/sftp_transfer.sh
scripts/utilities/sftp_transfer/sftp_transfer_crontab.sample

setup for cron, setup to cd to script directory, output date run, wrapped some of the verbose output in debug so we get a
more concise output

Cmoss 20250617 misc

---

terraform/aws/development-infrastructure/nbs-legacy/main.tf
terraform/aws/development-infrastructure/nbs-legacy/variables.tf

Add ability to stop scheduled tasks each day. Note this is for tasks with frequency < 1 day

add start/stop time

---

terraform/aws/development-infrastructure/sftp-lambda-preprocessor/lambda/lambda_split_csv/lambda_split_csv.py

rolling up some tested changes to csv conversion

fix for eol and MSH- delimiter

---

terraform/aws/development-infrastructure/nbs-legacy/README.md
terraform/aws/development-infrastructure/nbs-legacy/main.tf
terraform/aws/development-infrastructure/nbs-legacy/variables.tf

optional stop time. sometimes this hangs so it should be thoroughly tested in int before we push to test. default is set to disabled for now

Sgz add restart time
